### ISSUE TITLE
建议增加api消费的token数量

### ISSUE THREAD

**Issue by gaye746560359** [libli/chat#2]
建议增加分配的用户的令牌消费的token数量

**Comment by libli** [comment]
要一直统计token消费太麻烦了，可以限制每个用户的使用次数。

**Comment by gaye746560359** [comment]
> 要一直统计token消费太麻烦了，可以限制每个用户的使用次数。

好的。
非常期待大佬能增加阿里云函数部署。。数据库能支持外部mysql

**Comment by libli** [comment]
> > 要一直统计token消费太麻烦了，可以限制每个用户的使用次数。
> 
> 好的。 非常期待大佬能增加阿里云函数部署。。数据库能支持外部mysql

增加了MySQL支持，由于我海外服务器没部署MySQL，你测试一下看是否正常。
yaml按如下配置：
```
GinPort: 8080
OpenAIKey: "sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
Driver: "mysql"

MySQL:
  Host: ""
  Port: "3306"
  Username: ""
  Password: ""
  DBName: ""
```
docker使用1.1版本：
```
docker run --name=chatapi -d \
  --restart=unless-stopped -p 8080:8080 \
  -v /root/chat/config.yaml:/web/config.yaml \
  -v /root/chat/chat.db:/web/chat.db \
  libli/chat:1.1
```
