### ISSUE TITLE
config.yaml配置多token异常

### ISSUE THREAD

**Issue by young-qiang** [libli/chat#8]
配置文件如下：
```
GinPort: 8080
OpenAIKey:
  - "sk-****"
  - "sk-****"
DBName: "chat.db"
InitUsers:
  - Username: userAAA
    Token: abcd
  - Username: userBBB
    Token: bbcd
  - Username: user111
    Token: ddcd
```
启动后抛出异常：
`2023/06/29 11:53:35 failed to parse config file: yaml: unmarshal errors:
  line 4: cannot unmarshal !!seq into string`
